"""Regenerates the paper's data-driven figure (the four-stage debate arc).

    python papers/figures/_make_paper_figures.py

Reads `divergence_study_outputs/debate_full_arc.csv` and writes both PNG
(300 DPI) and PDF (vector) versions of:

    papers/figures/debate_full_arc.{png,pdf}

The conceptual pipeline overview (Figure 1 of the paper) is rendered inline
as a TikZ picture in `papers/position_paper.tex`, so it is not generated by
this script.

The figure is intentionally rendered with neutral typography and a small,
curated palette so it reads cleanly at the reduced sizes a 9-page NeurIPS
position paper imposes.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
FIG_DIR = REPO_ROOT / "papers" / "figures"
DATA_DIR = REPO_ROOT / "divergence_study_outputs"

FIG_DIR.mkdir(parents=True, exist_ok=True)

INK = "#1F1F1F"
MUTED = "#6B6B6B"
LIGHT = "#BDBDBD"
GRID = "#E6E6E6"
ACCENT = "#1F4E79"
WARN = "#A23B3B"

plt.rcParams.update(
    {
        "font.family": "serif",
        "font.serif": ["Times New Roman", "Times", "STIXGeneral", "DejaVu Serif"],
        "font.size": 9.5,
        "axes.titlesize": 10.5,
        "axes.labelsize": 9.5,
        "axes.edgecolor": INK,
        "axes.linewidth": 0.6,
        "xtick.color": INK,
        "ytick.color": INK,
        "xtick.labelsize": 8.5,
        "ytick.labelsize": 8.5,
        "legend.fontsize": 8.5,
        "legend.frameon": False,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.04,
    }
)


def save(fig, name: str) -> None:
    """Write both PNG (300 DPI) and PDF copies of `fig` under FIG_DIR/name."""
    png = FIG_DIR / f"{name}.png"
    pdf = FIG_DIR / f"{name}.pdf"
    fig.savefig(png, dpi=300)
    fig.savefig(pdf)
    print(f"  wrote {png.relative_to(REPO_ROOT)}  ({png.stat().st_size/1024:.0f} KB)")
    print(f"  wrote {pdf.relative_to(REPO_ROOT)}  ({pdf.stat().st_size/1024:.0f} KB)")


def make_debate_arc_figure() -> None:
    """The four-stage convergence arc, one summary line per generator with
    full-consensus as the headline trace and partial-convergence as a faint
    overlay. Per-scenario points are scattered to expose between-scenario
    spread."""
    df = pd.read_csv(DATA_DIR / "debate_full_arc.csv")

    stages = ["Closed\n(Sec.\u00a013)", "Open\n(Sec.\u00a014)", "Synthesis\n(Sec.\u00a015)", "Integrated\n(Sec.\u00a016)"]
    full_cols = ["sec13_consensus", "sec14_consensus", "sec15_full", "sec16_full"]
    partial_cols = [
        "sec13_consensus",
        "sec14_consensus",
        "sec15_partial",
        "sec16_majority",
    ]

    fig, ax = plt.subplots(figsize=(7.1, 3.1))

    gen_styles = {
        "gpt-5.4-nano": dict(color=ACCENT, marker="o", label="gpt-5.4-nano"),
        "gpt-4o": dict(color=WARN, marker="s", label="gpt-4o"),
    }

    x = np.arange(len(stages))
    jitter = {"gpt-5.4-nano": -0.06, "gpt-4o": +0.06}

    for gen, style in gen_styles.items():
        sub = df[df["gen_model"] == gen]
        full = sub[full_cols].values
        partial = sub[partial_cols].values

        full_mean = full.mean(axis=0)
        partial_mean = partial.mean(axis=0)

        ax.fill_between(
            x,
            full_mean,
            partial_mean,
            color=style["color"],
            alpha=0.07,
            linewidth=0,
            zorder=1,
        )
        ax.plot(
            x,
            partial_mean,
            color=style["color"],
            linestyle=(0, (4, 2)),
            linewidth=1.0,
            alpha=0.55,
            zorder=2,
        )
        for s in range(full.shape[0]):
            ax.scatter(
                x + jitter[gen],
                full[s],
                color=style["color"],
                alpha=0.22,
                s=14,
                linewidths=0,
                zorder=3,
            )
        ax.plot(
            x,
            full_mean,
            color=style["color"],
            marker=style["marker"],
            markersize=6.5,
            markeredgecolor="white",
            markeredgewidth=0.9,
            linewidth=1.9,
            label=style["label"],
            zorder=4,
        )

    ax.axhline(1.0, color=LIGHT, linewidth=0.6, linestyle=":", zorder=0)
    ax.set_xticks(x)
    ax.set_xticklabels(stages)
    ax.set_yticks(np.linspace(0, 1, 6))
    ax.set_yticklabels([f"{int(v*100)}%" for v in np.linspace(0, 1, 6)])
    ax.set_ylim(-0.04, 1.05)
    ax.set_ylabel("Across-scenario rate")
    ax.grid(axis="y", color=GRID, linewidth=0.6, zorder=0)
    ax.set_axisbelow(True)

    pivot_bbox = dict(
        boxstyle="round,pad=0.32",
        facecolor="white",
        edgecolor=LIGHT,
        linewidth=0.5,
        alpha=0.95,
    )
    callouts = [
        (0, 0.06, "6%", 0, 12, "center", "bottom", INK, None),
        (1, 0.09, "9%", 0, 12, "center", "bottom", INK, None),
        (2, 0.0, "0%", 0, 12, "center", "bottom", INK, None),
        (2, 1.0, "100%", -8, 6, "right", "bottom", INK, None),
        (3, 0.96, "95% full", -8, -6, "right", "top", INK, None),
        (3, 1.0, "100% majority", -8, 6, "right", "bottom", MUTED, None),
        (2.55, 0.22, "synthesis pivot\nfull \u2192 0%   partial \u2192 100%",
            0, 0, "center", "center", MUTED, pivot_bbox),
    ]
    for xi, yi, text, dx, dy, ha, va, color, bbox in callouts:
        ax.annotate(
            text,
            xy=(xi, yi),
            xytext=(dx, dy),
            textcoords="offset points",
            ha=ha,
            va=va,
            fontsize=7.8 if color is INK else 7.4,
            color=color,
            weight="bold" if color is INK else "normal",
            bbox=bbox,
            zorder=5,
        )

    handles, labels = ax.get_legend_handles_labels()
    series_full = plt.Line2D([], [], color=INK, linewidth=1.9, label="full consensus (mean)")
    series_partial = plt.Line2D(
        [], [], color=INK, linewidth=1.0, linestyle=(0, (4, 2)), alpha=0.55, label="partial convergence (mean)"
    )
    series_scatter = plt.Line2D(
        [], [], color=INK, alpha=0.4, marker="o", linewidth=0, markersize=4, label="per-scenario (full)"
    )
    legend = ax.legend(
        handles=handles + [series_full, series_partial, series_scatter],
        loc="center left",
        bbox_to_anchor=(1.01, 0.5),
        ncol=1,
        handlelength=2.2,
        handletextpad=0.6,
        labelspacing=0.55,
        borderaxespad=0.0,
    )
    legend.get_frame().set_alpha(0.0)

    fig.tight_layout()
    save(fig, "debate_full_arc")
    plt.close(fig)


def main() -> None:
    print("Generating debate_full_arc...")
    make_debate_arc_figure()


if __name__ == "__main__":
    main()
