"""
scripts/make_iclr_figures.py -- figure and table sources for papers/iclr2027, generated from
the committed artefacts only (every number carries a % source comment in the output).

  figures/fig_judge_panel.tex    pillar 1: NoT minus CoT validation drop per generator under
                                 every judge of the 17.8 panel (and, when present, the 17.10
                                 same-day 4,096-token replicate under the production judge)
  figures/tab_routing.tex        pillar 3: collective, routed, routing gain per condition
                                 (verify_pillar3_headline_*.json) and the 16.28 seat contrast

Missing artefacts are skipped and listed in the output header, never silently zero-filled.

Run:  python -m scripts.make_iclr_figures
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path("divergence_study_outputs")
FIG = Path("papers/iclr2027/figures")
GENS = [("claude-haiku-4-5", "haiku"), ("claude-sonnet-4-6", "sonnet"), ("gpt-5.4-nano", "nano"),
        ("grok-4-1-fast-reasoning", "grok"), ("Llama-3.3-70B-Instruct", "Llama"),
        ("Mistral-Large-3-2", "Mistral"), ("DeepSeek-V4-Pro", "DeepSeek")]
JUDGES = [("claude-haiku-4-5", "haiku (production)", "teal!75!black", "*"),
          ("gpt-4o", "gpt-4o", "orange!85!black", "square*"),
          ("gpt-5.4-nano", "nano", "violet!80!black", "triangle*"),
          ("Llama-3.3-70B-Instruct", "Llama", "gray!80!black", "diamond*"),
          ("grok-4-1-fast-reasoning", "grok", "red!70!black", "pentagon*")]
CONDITIONS = [("grok", "grok, edges on (primary)"), ("noedge", "grok, edges off"),
              ("haiku_249", "haiku"), ("llama", "Llama"), ("deepseek", "DeepSeek"), ("mistral", "Mistral")]


def _load(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def judge_panel_figure() -> str:
    missing, series = [], []
    for jk, jl, col, mark in JUDGES:
        d = _load(OUT / f"judge_panel_full_oeq_{jk}.json")
        if d is None:
            missing.append(jk)
            continue
        pg = d["judges"][jk]["per_generator"]
        pts = []
        for gi, (gk, gl) in enumerate(GENS):
            c = pg.get(gk, {}).get("narrative_cot")
            if not c or c.get("drop") is None:
                continue
            pts.append((gi, 100 * c["drop"], 100 * c["lo"], 100 * c["hi"], gl))
        series.append((jk, jl, col, mark, pts))
    k = len(series)
    lines = ["% AUTO-GENERATED by scripts/make_iclr_figures.py from judge_panel_full_oeq_<judge>.json (17.8).",
             f"% judges missing at generation time: {missing or 'none'}",
             "\\begin{tikzpicture}",
             "\\begin{axis}[width=\\columnwidth, height=6.2cm, xmin=-85, xmax=20,",
             "  xlabel={NoT $-$ standard CoT, validation rate (points)},",
             f"  ytick={{{','.join(str(i) for i in range(len(GENS)))}}},",
             f"  yticklabels={{{','.join(g[1] for g in GENS)}}}, y dir=reverse,",
             "  ymin=-0.6, ymax=6.6, xmajorgrids, axis lines*=left, yticklabel style={font=\\small},",
             "  legend style={font=\\scriptsize, at={(0.99,0.02)}, anchor=south east, draw=none, fill=white, fill opacity=0.8, text opacity=1},",
             "  legend cell align=left]",
             "\\addplot[black, dashed, forget plot] coordinates {(0,-0.6) (0,6.6)};"]
    for si, (jk, jl, col, mark, pts) in enumerate(series):
        off = (si - (k - 1) / 2) * 0.14
        lines.append(f"\\addplot[only marks, mark={mark}, mark size=1.7pt, color={col}, "
                     "error bars/.cd, x dir=both, x explicit, error bar style={line width=0.5pt}]")
        lines.append("  coordinates {")
        for gi, dr, lo, hi, gl in pts:
            lines.append(f"    ({dr:.1f},{gi + off:.2f}) -= ({dr - lo:.1f},0) += ({hi - dr:.1f},0)"
                         f"  % {gl}: {dr:+.1f} [{lo:+.1f}, {hi:+.1f}]")
        lines.append("  };")
        lines.append(f"\\addlegendentry{{{jl}}}")
    lines += ["\\end{axis}", "\\end{tikzpicture}"]
    return "\n".join(lines) + "\n"


def routing_table() -> str:
    rows, missing = [], []
    for ck, cl in CONDITIONS:
        v = _load(OUT / f"verify_pillar3_headline_{ck}.json")
        if v is None:
            missing.append(ck)
            continue
        r = v["recomputed"]
        rows.append((cl, r["collective"], r["routed"], r["delta"], r["lo"], r["hi"], r["fire"], r["n"],
                     v.get("all_agree")))
    out = ["% AUTO-GENERATED by scripts/make_iclr_figures.py from verify_pillar3_headline_<cond>.json",
           "% (independent recomputation; sonnet standard majority-of-3 judge on flagged debates).",
           f"% conditions missing at generation time: {missing or 'none'}",
           "\\begin{tabular}{lrrrrr}", "\\toprule",
           "condition & $n$ & fire & collective & routed & routed $-$ collective \\\\", "\\midrule"]
    for cl, coll, rt, d, lo, hi, fire, n, agree in rows:
        out.append(f"{cl} & {n} & {fire:.2f} & {coll:.3f} & {rt:.3f} & "
                   f"$+{100 * d:.1f}$ [{100 * lo:+.1f}, {100 * hi:+.1f}] \\\\"
                   f"  % verify all_agree={agree}")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def main() -> int:
    FIG.mkdir(parents=True, exist_ok=True)
    (FIG / "fig_judge_panel.tex").write_text(judge_panel_figure())
    (FIG / "tab_routing.tex").write_text(routing_table())
    print("wrote", FIG / "fig_judge_panel.tex", FIG / "tab_routing.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
