"""
scripts/make_iclr_figures.py -- figure and table sources for papers/iclr2027, generated from
the committed artefacts only (every number carries a % source comment in the output).

  figures/fig_judge_panel.tex    pillar 1: NoT minus CoT validation drop per generator under
                                 every judge of the 17.8 panel (and, when present, the 17.10
                                 same-day 4,096-token replicate under the production judge)
  figures/tab_routing.tex        pillar 3: collective, routed, routing gain per condition
                                 (verify_pillar3_headline_*.json) and the 16.28 seat contrast

Missing artefacts are skipped and listed in the output header, never silently zero-filled.

Run:  python -m scripts.make_iclr_figures
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path("divergence_study_outputs")
FIG = Path("papers/iclr2027/figures")
GENS = [("claude-haiku-4-5", "haiku"), ("claude-sonnet-4-6", "sonnet"), ("gpt-5.4-nano", "nano"),
        ("grok-4-1-fast-reasoning", "grok"), ("Llama-3.3-70B-Instruct", "Llama"),
        ("Mistral-Large-3-2", "Mistral"), ("DeepSeek-V4-Pro", "DeepSeek")]
JUDGES = [("claude-haiku-4-5", "haiku (production)", "teal!75!black", "*"),
          ("gpt-4o", "gpt-4o", "orange!85!black", "square*"),
          ("gpt-5.4-nano", "nano", "violet!80!black", "triangle*"),
          ("Llama-3.3-70B-Instruct", "Llama", "gray!80!black", "diamond*"),
          ("grok-4-1-fast-reasoning", "grok", "red!70!black", "pentagon*")]
CONDITIONS = [("grok", "grok, edges on (primary)"), ("noedge", "grok, edges off"),
              ("haiku_249", "haiku"), ("llama", "Llama"), ("deepseek", "DeepSeek"), ("mistral", "Mistral")]


def _load(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def judge_panel_figure() -> str:
    missing, series = [], []
    for jk, jl, col, mark in JUDGES:
        d = _load(OUT / f"judge_panel_full_oeq_{jk}.json")
        if d is None:
            missing.append(jk)
            continue
        pg = d["judges"][jk]["per_generator"]
        pts = []
        for gi, (gk, gl) in enumerate(GENS):
            c = pg.get(gk, {}).get("narrative_cot")
            if not c or c.get("drop") is None:
                continue
            pts.append((gi, 100 * c["drop"], 100 * c["lo"], 100 * c["hi"], gl))
        series.append((jk, jl, col, mark, pts))
    k = len(series)
    lines = ["% AUTO-GENERATED by scripts/make_iclr_figures.py from judge_panel_full_oeq_<judge>.json (17.8).",
             f"% judges missing at generation time: {missing or 'none'}",
             "\\begin{tikzpicture}",
             "\\begin{axis}[width=\\columnwidth, height=6.2cm, xmin=-85, xmax=25,",
             "  xlabel={NoT $-$ standard CoT, validation rate (points)},",
             f"  ytick={{{','.join(str(i) for i in range(len(GENS)))}}},",
             f"  yticklabels={{{','.join(g[1] for g in GENS)}}}, y dir=reverse,",
             "  ymin=-0.6, ymax=6.6, xmajorgrids, axis lines*=left, yticklabel style={font=\\small},",
             "  legend style={font=\\scriptsize, at={(0.5,1.02)}, anchor=south, legend columns=5, draw=none},",
             "  legend cell align=left]",
             "\\addplot[black, dashed, forget plot] coordinates {(0,-0.6) (0,6.6)};"]
    for si, (jk, jl, col, mark, pts) in enumerate(series):
        off = (si - (k - 1) / 2) * 0.14
        lines.append(f"\\addplot[only marks, mark={mark}, mark size=1.7pt, color={col}, "
                     "error bars/.cd, x dir=both, x explicit, error bar style={line width=0.5pt}]")
        lines.append("  coordinates {")
        for gi, dr, lo, hi, gl in pts:
            lines.append(f"    ({dr:.1f},{gi + off:.2f}) -= ({dr - lo:.1f},0) += ({hi - dr:.1f},0)"
                         f"  % {gl}: {dr:+.1f} [{lo:+.1f}, {hi:+.1f}]")
        lines.append("  };")
        lines.append(f"\\addlegendentry{{{jl}}}")
    lines += ["\\end{axis}", "\\end{tikzpicture}"]
    return "\n".join(lines) + "\n"


def routing_table() -> str:
    rows, missing = [], []
    for ck, cl in CONDITIONS:
        v = _load(OUT / f"verify_pillar3_headline_{ck}.json")
        if v is None:
            missing.append(ck)
            continue
        r = v["recomputed"]
        rows.append((cl, r["collective"], r["routed"], r["delta"], r["lo"], r["hi"], r["fire"], r["n"],
                     v.get("all_agree")))
    out = ["% AUTO-GENERATED by scripts/make_iclr_figures.py from verify_pillar3_headline_<cond>.json",
           "% (independent recomputation; sonnet standard majority-of-3 judge on flagged debates).",
           f"% conditions missing at generation time: {missing or 'none'}",
           "\\begin{tabular}{lrrrrr}", "\\toprule",
           "condition & $n$ & fire & collective & routed & routed $-$ collective \\\\", "\\midrule"]
    for cl, coll, rt, d, lo, hi, fire, n, agree in rows:
        out.append(f"{cl} & {n} & {fire:.2f} & {coll:.3f} & {rt:.3f} & "
                   f"$+{100 * d:.1f}$ [{100 * lo:+.1f}, {100 * hi:+.1f}] \\\\"
                   f"  % verify all_agree={agree}")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


JUDGE_SHORT = {"claude-haiku-4-5": "haiku (prod.)", "gpt-4o": "gpt-4o", "gpt-5.4-nano": "nano",
               "Llama-3.3-70B-Instruct": "Llama", "grok-4-1-fast-reasoning": "grok"}


def _ci(c, scale=100):
    # Interval in math mode so its minus signs match the point estimate's (appendix tables).
    return f"${scale * c['point']:+.1f}$ $[{scale * c['lo']:+.1f}, {scale * c['hi']:+.1f}]$"


def form_table() -> str:
    d = _load(OUT / "narrative_form_readout.json")
    if d is None:
        return "% narrative_form_readout.json not present\n"
    out = ["% AUTO-GENERATED from narrative_form_readout.json (17.7, 17.7 amendment 2, 17.4; same-day",
           "% replicates standard_cot_rep / narrative_cot_rep as comparators; pooled over haiku, grok, nano, Llama;",
           "% item-clustered bootstrap). Drop = arm minus CoT, points; share = arm's drop over NoT's drop.",
           "\\begin{tabular}{llrrl}", "\\toprule",
           "judge & arm & drop from CoT & share of NoT & reading \\\\", "\\midrule"]
    for j, jr in d["judges"].items():
        f = jr["form_pooled"]
        ck, no, pc = f["checklist"], f["narrative_only"], jr.get("persona_pooled", {})
        if ck.get("drop_arm") is None:
            continue
        out.append(f"{JUDGE_SHORT.get(j, j)} & NoT & {_ci(ck['drop_not'])} & 1.00 & \\\\")
        out.append(f" & checklist, same content & {_ci(ck['drop_arm'])} & {ck['share']['point']:.2f} & {jr['form_reading']['checklist']} \\\\")
        out.append(f" & narrative only & {_ci(no['drop_arm'])} & {no['share']['point']:.2f} & {jr['form_reading']['narrative_only']} \\\\")
        if pc.get("drop_arm") is not None:
            out.append(f" & persona only & {_ci(pc['drop_arm'])} & {pc['share']['point']:.2f} & {jr.get('persona_reading', '')} \\\\")
        out.append("\\addlinespace")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def rep4k_table() -> str:
    d = _load(OUT / "headline_rep4k_readout.json")
    if d is None:
        return "% headline_rep4k_readout.json not present\n"
    # Columns in the order of the five-judge panel (JUDGES), not the artefact's order, so this table
    # reads against tab-app-judge-drops and Figure 1; every cell carries its item-clustered interval.
    order = [jk for jk, *_ in JUDGES]
    judges = [j for j in order if j in d["judges"]] + [j for j in d["judges"] if j not in order]
    out = ["% AUTO-GENERATED from headline_rep4k_readout.json (17.10: same-day, both arms at 4,096 tokens).",
           "\\begin{tabular}{l" + "r" * len(judges) + "l}", "\\toprule",
           "generator & " + " & ".join(JUDGE_SHORT.get(j, j) for j in judges) + " & reading \\\\", "\\midrule"]
    for gk, gl in GENS:
        v = d["per_generator"].get(gk)
        if not v:
            continue
        cells = []
        for j in judges:
            c = v["per_judge"].get(j, {})
            cells.append("--" if c.get("drop") is None else
                         f"${100 * c['drop']:+.1f}$ $[{100 * c['lo']:+.1f}, {100 * c['hi']:+.1f}]$")
        out.append(f"{gl} & " + " & ".join(cells) + f" & {v['reading'].replace('HEADLINE-', '')} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def pushback_table() -> str:
    rows = []
    for m, lab in (("gpt-5.4-nano", "nano"), ("Llama-3.3-70B-Instruct", "Llama"), ("grok-4-1-fast-reasoning", "grok")):
        short = {"gpt-5.4-nano": "nano", "Llama-3.3-70B-Instruct": "llama", "grok-4-1-fast-reasoning": "grok"}[m]
        d = _load(OUT / f"pushback_readout_{short}.json")
        if d is None:
            continue
        pm = d["per_model"][m]
        rows.append((lab, pm["n_common_support"], pm.get("cap"), pm.get("inst"), pm.get("net")))
    pooled = _load(OUT / "pushback_readout_pooled.json")
    out = ["% AUTO-GENERATED from pushback_readout_{nano,llama,grok,pooled}.json (17.9; haiku unread, guard).",
           "\\begin{tabular}{lrrrr}", "\\toprule",
           "model & items & capitulation CoT / NoT & re-ask CoT / NoT & net NoT $-$ CoT \\\\", "\\midrule"]

    def fmt(v):
        return "--" if not v else f"{v['cot']:.2f} / {v['not']:.2f}"

    def net(v):
        if not v or not v.get("not_minus_cot"):
            return "--"
        x = v["not_minus_cot"]
        return f"${100 * x['diff']:+.1f}$ $[{100 * x['lo']:+.1f}, {100 * x['hi']:+.1f}]$"
    for lab, n, cap, inst, nt in rows:
        out.append(f"{lab} & {n} & {fmt(cap)} & {fmt(inst)} & {net(nt)} \\\\")
    if pooled:
        p = pooled["pooled"]
        out.append("\\midrule")
        out.append(f"pooled & {p['cap']['not_minus_cot']['n_pairs']} & {fmt(p.get('cap'))} & {fmt(p.get('inst'))} & {net(p.get('net'))} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def seat_table() -> str:
    d = _load(OUT / "seat_scaffold_comparison.json")
    if d is None:
        return "% seat_scaffold_comparison.json not present\n"
    out = ["% AUTO-GENERATED from seat_scaffold_comparison.json (16.28; narrated minus plain-CoT seats, paired items).",
           "\\begin{tabular}{lrr}", "\\toprule", "readout & grok & Llama \\\\", "\\midrule"]
    names = [("acc", "collective accuracy"), ("routed", "routed accuracy"),
             ("routed_matched", "routed, matched coverage"), ("gain", "routing gain"), ("fire", "fire rate")]
    for k, lab in names:
        cells = []
        for m in ("grok", "llama"):
            v = d["per_model"][m][k]
            cells.append(f"${100 * v['diff']:+.1f}$ $[{100 * v['lo']:+.1f}, {100 * v['hi']:+.1f}]$")
        out.append(f"{lab} & " + " & ".join(cells) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def main() -> int:
    FIG.mkdir(parents=True, exist_ok=True)
    (FIG / "fig_judge_panel.tex").write_text(judge_panel_figure())
    (FIG / "tab_routing.tex").write_text(routing_table())
    (FIG / "tab_form.tex").write_text(form_table())
    (FIG / "tab_rep4k.tex").write_text(rep4k_table())
    (FIG / "tab_pushback.tex").write_text(pushback_table())
    (FIG / "tab_seat.tex").write_text(seat_table())
    print("wrote", FIG / "fig_judge_panel.tex", FIG / "tab_routing.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
